### PR TITLE
v15.0

### LINKED ISSUE #794: mattermost - can't log in after first boot
**[update]** It seems the issue is that Mattermost asks for 'email address" when logging in, but actually you need to supply the username (`admin`). This issue needs to be resolved upstream. In the meantime, we need to provide better documented to assist users.

----

A user reported that after doing firstboot initialisation they weren't able to log in to Mattermost using their username and password. 

I haven't yet confirmed it, but this needs to be doublechecked, at least before next release.

### PR DESCRIPTION
**Pull request by qq7**
closes https://github.com/turnkeylinux/tracker/issues/794

### CODE REVIEW

**Comment by JedMeister** [comment]
Hey @qq7 - looks good mate, but does this actually address the fix noted in https://github.com/turnkeylinux/tracker/issues/794#issuecomment-371295609 ?

I would think that you'd need to add a couple more sed lines (updating `EnableSignInWithUsername` & `EnableSignInWithEmail` to be true) to fix that issue? Or are they set by default?

**Comment by JedMeister** [comment]
This one needs an updated changelog too.

**Comment by qq7** [comment]
The problem was that the Python inithook wasn't changing email, so now when
it's fixed, the user would be able to log in using their email.

Apologies re changelogs, it slipped my mind completely. I'll push them for
this and other appliances as soon as I get to a computer.

вт, 3 апр. 2018 г., 2:59 Jeremy Davis <notifications@github.com>:

**Comment by JedMeister** [comment]
> The problem was that the Python inithook wasn't changing email, so now when it's fixed, the user would be able to log in using their email.

Perfect, thanks mate! :smile: 

> Apologies re changelogs, it slipped my mind completely. I'll push them for this and other appliances as soon as I get to a computer.

No worries. I know how it happens... I'll leave this (and the other one) open for now so you can just add it and push to the same branch and it will auto show up here! :smile:

**Comment by qq7** [comment]
@JedMeister done

**Pull request merged**
