### PR TITLE
update for 18.0

### PR DESCRIPTION
**Pull request by OnGle**

### CODE REVIEW

**Comment by OnGle** [comment]
now requires https://github.com/turnkeylinux/common/pull/264

**Comment by JedMeister** [comment]
Needs a changelog. :)

**Comment by AndreasMurk** [comment]
Is there any update for the new versions for Mattermost? My phone already gives me some warnings regarding outdated server version. Thanks :)

**Comment by OnGle** [comment]
@AndreasMurk ideally within the next couple of weeks, we released in batches of 10, ideally that means every 2 or so weeks but some appliances are either more work to build/test/update or all of the above so unfortunately I can't give a concrete time frame. Also this is a PR I forgot to close in favor of the newer https://github.com/turnkeylinux-apps/mattermost/pull/14 of which I'm very late on reviewing, sorry :grimacing: hopefully I'll have that part done by monday and we'll just be waiting for the next batch of 10 from there :)

**Pull request closed without merging**
